tableName_games = 'erbs_games'
tableName_stats = 'erbs_stats'
tableName_data = 'erbs_data'

game_data_type = {
    "userNum": "INT",
    "nickname": "VARCHAR(255)",
    "gameId": "INT",
    "seasonId": "INT",
    "matchingMode": "INT",
    "matchingTeamMode": "INT",
    "characterNum": "INT",
    "skinCode": "INT",
    "characterLevel": "INT",
    "gameRank": "INT",
    "playerKill": "INT",
    "playerAssistant": "INT",
    "monsterKill": "INT",
    "bestWeapon": "INT",
    "bestWeaponLevel": "INT",
    "masteryLevel": "JSON",
    "equipment": "JSON",
    "versionMajor": "INT",
    "versionMinor": "INT",
    "skillLevelInfo": "JSON",
    "skillOrderInfo": "JSON",
    "serverName": "VARCHAR(100)",
    "maxHp": "INT",
    "maxSp": "INT",
    "attackPower": "INT",
    "defense": "INT",
    "hpRegen": "DOUBLE",
    "spRegen": "DOUBLE",
    "attackSpeed": "DOUBLE",
    "moveSpeed": "DOUBLE",
    "outOfCombatMoveSpeed": "DOUBLE",
    "sightRange": "DOUBLE",
    "attackRange": "DOUBLE",
    "criticalStrikeChance": "INT",
    "criticalStrikeDamage": "INT",
    "coolDownReduction": "INT",
    "lifeSteal": "INT",
    "amplifierToMonster": "INT",
    "trapDamage": "INT",
    "gainExp": "INT",
    "startDtm": "datetime",
    "duration": "INT",
    "mmrBefore": "INT",
    "killerUserNum": "INT",
    "playTime": "INT",
    "watchTime": "INT",
    "totalTime": "INT",
    "botAdded": "INT",
    "botRemain": "INT",
    "restrictedAreaAccelerated": "INT",
    "safeAreas": "INT",
    "killer": "VARCHAR(100)",
    "killDetail": "VARCHAR(100)",
    "causeOfDeath": "VARCHAR(200)",
    "teamNumber": "INT",
    "preMade": "INT",
    "gainedNormalMmrKFactor": "DOUBLE",
    "victory": "INT",
    "craftUncommon": "INT",
    "craftRare": "INT",
    "craftEpic": "INT",
    "craftLegend": "INT",
    "damageToPlayer": "INT",
    "damageToPlayer_trap": "INT",
    "damageToPlayer_basic": "INT",
    "damageToPlayer_skill": "INT",
    "damageToPlayer_direct": "INT",
    "damageFromPlayer": "INT",
    "damageFromPlayer_trap": "INT",
    "damageFromPlayer_basic": "INT",
    "damageFromPlayer_skill": "INT",
    "damageFromPlayer_direct": "INT",
    "damageToMonster": "INT",
    "damageToMonster_trap": "INT",
    "damageToMonster_basic": "INT",
    "damageToMonster_skill": "INT",
    "damageToMonster_direct": "INT",
    "damageFromMonster": "INT",
    "killMonsters": "JSON",
    "healAmount": "INT",
    "teamRecover": "INT",
    "protectAbsorb": "INT",
    "addSurveillanceCamera": "INT",
    "addTelephotoCamera": "INT",
    "removeSurveillanceCamera": "INT",
    "removeTelephotoCamera": "INT",
    "useHyperLoop": "INT",
    "useSecurityConsole": "INT",
    "giveUp": "INT",
    "teamSpectator": "INT",
    "routeIdOfStart": "INT",
    "placeOfStart": "VARCHAR(100)",
    "placeOfDeath": "VARCHAR(100)",
    "killerCharacter": "VARCHAR(100)",

    "trapDamageToPlayer": "INT",
    "basicAttackDamageToPlayer": "INT",
    "skillDamageToPlayer": "INT",
}
stats_data_type = {
    "seasonId": "INT",
    "userNum": "INT",
    "matchingMode": "INT",
    "matchingTeamMode": "INT",
    "mmr": "INT",
    "nickname": "VARCHAR(255)",
    "rank": "INT",
    "rankSize": "INT",
    "totalGames": "INT",
    "totalWins": "INT",
    "rankPercent": "DOUBLE",
    "averageRank": "DOUBLE",
    "averageKills": "DOUBLE",
    "averageAssistants": "DOUBLE",
    "averageHunts": "DOUBLE",
    "top1": "INT",
    "top2": "INT",
    "top3": "INT",
    "top5": "INT",
    "top7": "INT",
    "characterStats": "VARCHAR(500)",
}

# games
init_games_DB = f"CREATE TABLE IF NOT EXISTS {tableName_games}(" \
                f"no    INT NOT NULL AUTO_INCREMENT PRIMARY KEY, "
for data_name, data_type in game_data_type.items():
    init_games_DB += f"{data_name} {data_type}, "

init_games_DB += f"time  datetime  NOT NULL DEFAULT CURRENT_TIMESTAMP);"

# stats
init_stats_DB = f"CREATE TABLE IF NOT EXISTS {tableName_stats}(" \
                f"no    INT NOT NULL AUTO_INCREMENT PRIMARY KEY, "
for data_name, data_type in stats_data_type.items():
    init_stats_DB += f"{data_name} {data_type}, "

init_stats_DB += f"time  datetime  NOT NULL DEFAULT CURRENT_TIMESTAMP);"

